name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: 'Make Release'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@17

  wiki:
    name: 'Update wiki'
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout self'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Checkout wiki'
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          fetch-depth: 0
          path: wiki
      - name: Render terraform docs
        uses: Dirrk/terraform-docs@v1.0.8
        with:
          tf_docs_output_method: replace
          tf_docs_content_type: table
          tf_docs_output_file: wiki/Home.md
      - name: Push docs changes to wiki
        run: |
          git status
          doCommit=$(git diff-index --quiet HEAD -- || echo true)
          echo $doCommit
          if [ $doCommit ]
          then
            git config user.name terraform-docs
            git config user.email actions@github.com
            git add Home.md
            git commit -m "Updated documentation"
            git push
          else
            echo "No changes to be commited."
          fi
        working-directory: wiki/
